CREATE TABLE api_keys (
  id         INTEGER PRIMARY KEY AUTOINCREMENT
  , user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE
  , key        TEXT NOT NULL
  , created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  , UNIQUE(user_id, key)
);